---
title: "Reporting Variables"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reporting_Variables}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The `gcamreport` package standardizes variables for reporting, which facilitates multi-model comparison projects. It follows the naming conventions, definitions, and units established by the [`openentrance`](https://github.com/openENTRANCE/openentrance) project, ensuring consistency across models. To compute global values for reported variables, the package applies different methodologies based on the characteristics of each variable. Below, you'll find a detailed list of all reported variables and their respective computational procedures. In the standardized datasets, these global values are categorized under the ``World'' region.

| Reported variable                                                       | World value computational procedure                                |
| ----------------------------------------------------------------------- | ------------------------------------------------------------------ |
| Agricultural Demand                                                     | Sum of regional values                                             |
| Agricultural Demand\|Crops                                              | Sum of regional values                                             |
| Agricultural Demand\|Crops\|Energy                                      | Sum of regional values                                             |
| Agricultural Demand\|Crops\|Feed                                        | Sum of regional values                                             |
| Agricultural Demand\|Crops\|Food                                        | Sum of regional values                                             |
| Agricultural Demand\|Crops\|Other                                       | Sum of regional values                                             |
| Agricultural Demand\|Livestock                                          | Sum of regional values                                             |
| Agricultural Demand\|Livestock\|Food                                    | Sum of regional values                                             |
| Agricultural Demand\|Livestock\|Other                                   | Sum of regional values                                             |
| Agricultural Production                                                 | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Biomass                                | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Biomass\|w/ CCS                        | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Biomass\|w/o CCS                       | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Coal                                   | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Coal\|w/ CCS                           | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Coal\|w/o CCS                          | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Gas                                    | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Gas\|w/ CCS                            | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Gas\|w/o CCS                           | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Geothermal                             | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Nuclear                                | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Oil                                    | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Oil\|w/ CCS                            | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Oil\|w/o CCS                           | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Solar                                  | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Solar\|CSP                             | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Solar\|PV                              | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Wind                                   | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Wind\|Offshore                         | Sum of regional values                                             |
| Capacity Additions\|Electricity\|Wind\|Onshore                          | Sum of regional values                                             |
| Capacity\|Electricity                                                   | Sum of regional values                                             |
| Capacity\|Electricity\|Biomass                                          | Sum of regional values                                             |
| Capacity\|Electricity\|Biomass\|w/ CCS                                  | Sum of regional values                                             |
| Capacity\|Electricity\|Biomass\|w/o CCS                                 | Sum of regional values                                             |
| Capacity\|Electricity\|Coal                                             | Sum of regional values                                             |
| Capacity\|Electricity\|Coal\|w/ CCS                                     | Sum of regional values                                             |
| Capacity\|Electricity\|Coal\|w/o CCS                                    | Sum of regional values                                             |
| Capacity\|Electricity\|Gas                                              | Sum of regional values                                             |
| Capacity\|Electricity\|Gas\|w/ CCS                                      | Sum of regional values                                             |
| Capacity\|Electricity\|Gas\|w/o CCS                                     | Sum of regional values                                             |
| Capacity\|Electricity\|Geothermal                                       | Sum of regional values                                             |
| Capacity\|Electricity\|Hydro                                            | Sum of regional values                                             |
| Capacity\|Electricity\|Nuclear                                          | Sum of regional values                                             |
| Capacity\|Electricity\|Oil                                              | Sum of regional values                                             |
| Capacity\|Electricity\|Oil\|w/ CCS                                      | Sum of regional values                                             |
| Capacity\|Electricity\|Oil\|w/o CCS                                     | Sum of regional values                                             |
| Capacity\|Electricity\|Solar                                            | Sum of regional values                                             |
| Capacity\|Electricity\|Solar\|CSP                                       | Sum of regional values                                             |
| Capacity\|Electricity\|Solar\|PV                                        | Sum of regional values                                             |
| Capacity\|Electricity\|Wind                                             | Sum of regional values                                             |
| Capacity\|Electricity\|Wind\|Offshore                                   | Sum of regional values                                             |
| Capacity\|Electricity\|Wind\|Onshore                                    | Sum of regional values                                             |
| Capital Cost\|Electricity\|Biomass\|w/ CCS                              | Sum of regional values                                             |
| Capital Cost\|Electricity\|Biomass\|w/o CCS                             | Mean of regional values                                            |
| Capital Cost\|Electricity\|Coal\|w/ CCS                                 | Mean of regional values                                            |
| Capital Cost\|Electricity\|Coal\|w/o CCS                                | Mean of regional values                                            |
| Capital Cost\|Electricity\|Gas\|w/ CCS                                  | Mean of regional values                                            |
| Capital Cost\|Electricity\|Gas\|w/o CCS                                 | Mean of regional values                                            |
| Capital Cost\|Electricity\|Geothermal                                   | Mean of regional values                                            |
| Capital Cost\|Electricity\|Nuclear                                      | Mean of regional values                                            |
| Capital Cost\|Electricity\|Solar\|CSP                                   | Mean of regional values                                            |
| Capital Cost\|Electricity\|Solar\|PV                                    | Mean of regional values                                            |
| Capital Cost\|Electricity\|Wind\|Offshore                               | Mean of regional values                                            |
| Capital Cost\|Electricity\|Wind\|Onshore                                | Mean of regional values                                            |
| Carbon Sequestration\|CCS                                               | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Biomass                                      | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Biomass\|Energy\|Demand\|Industry            | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Biomass\|Energy\|Supply                      | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Biomass\|Energy\|Supply\|Electricity         | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Biomass\|Energy\|Supply\|Hydrogen            | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Biomass\|Energy\|Supply\|Liquids             | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Fossil                                       | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Fossil\|Energy\|Demand\|Industry             | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Fossil\|Energy\|Supply                       | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Fossil\|Energy\|Supply\|Electricity          | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Fossil\|Energy\|Supply\|Hydrogen             | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Fossil\|Energy\|Supply\|Liquids              | Sum of regional values                                             |
| Carbon Sequestration\|CCS\|Industrial Processes                         | Sum of regional values                                             |
| Carbon Sequestration\|Direct Air Capture                                | Sum of regional values                                             |
| Concentration\|CO2                                                      | Global value                                                       |
| Emissions\|BC                                                           | Sum of regional values                                             |
| Emissions\|BC\|AFOLU                                                    | Sum of regional values                                             |
| Emissions\|BC\|Energy                                                   | Sum of regional values                                             |
| Emissions\|BC\|Energy\|Demand\|Industry                                 | Sum of regional values                                             |
| Emissions\|BC\|Energy\|Demand\|Residential and Commercial               | Sum of regional values                                             |
| Emissions\|BC\|Energy\|Demand\|Transportation                           | Sum of regional values                                             |
| Emissions\|BC\|Energy\|Supply                                           | Sum of regional values                                             |
| Emissions\|C2F6                                                         | Sum of regional values                                             |
| Emissions\|CF4                                                          | Sum of regional values                                             |
| Emissions\|CH4                                                          | Sum of regional values                                             |
| Emissions\|CH4\|AFOLU                                                   | Sum of regional values                                             |
| Emissions\|CH4\|Energy                                                  | Sum of regional values                                             |
| Emissions\|CH4\|Energy\|Demand\|Industry                                | Sum of regional values                                             |
| Emissions\|CH4\|Energy\|Demand\|Residential and Commercial              | Sum of regional values                                             |
| Emissions\|CH4\|Energy\|Demand\|Transportation                          | Sum of regional values                                             |
| Emissions\|CH4\|Energy\|Supply                                          | Sum of regional values                                             |
| Emissions\|CH4\|Other                                                   | Sum of regional values                                             |
| Emissions\|CO                                                           | Sum of regional values                                             |
| Emissions\|CO\|AFOLU                                                    | Sum of regional values                                             |
| Emissions\|CO\|Energy                                                   | Sum of regional values                                             |
| Emissions\|CO\|Energy\|Demand\|Industry                                 | Sum of regional values                                             |
| Emissions\|CO\|Energy\|Demand\|Residential and Commercial               | Sum of regional values                                             |
| Emissions\|CO\|Energy\|Demand\|Transportation                           | Sum of regional values                                             |
| Emissions\|CO\|Energy\|Supply                                           | Sum of regional values                                             |
| Emissions\|CO2                                                          | Sum of regional values                                             |
| Emissions\|CO2\|AFOLU                                                   | Sum of regional values                                             |
| Emissions\|CO2\|Energy                                                  | Sum of regional values                                             |
| Emissions\|CO2\|Energy and Industrial Processes                         | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand                                          | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|AFOFI                                   | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Industry                                | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Industry\|Cement                        | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Industry\|Chemicals                     | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Industry\|Chemicals\|Ammonia            | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Industry\|Non-ferrous metals            | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Industry\|Other                         | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Industry\|Steel                         | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Residential and Commercial              | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Residential and Commercial\|Commercial  | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Residential and Commercial\|Residential | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Transportation                          | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Transportation\|Freight                 | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Demand\|Transportation\|Passenger               | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Supply                                          | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Supply\|Electricity                             | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Supply\|Gases                                   | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Supply\|Heat                                    | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Supply\|Liquids                                 | Sum of regional values                                             |
| Emissions\|CO2\|Energy\|Supply\|Solids                                  | Sum of regional values                                             |
| Emissions\|CO2\|Industrial Processes                                    | Sum of regional values                                             |
| Emissions\|CO2\|Other Removal                                           | Sum of regional values                                             |
| Emissions\|CO2\|Other Removal\|DACCS                                    | Sum of regional values                                             |
| Emissions\|CO2\|Other                                                   | Sum of regional values                                             |
| Emissions\|F-Gases                                                      | Sum of regional values                                             |
| Emissions\|HFC                                                          | Sum of regional values                                             |
| Emissions\|HFC\|HFC125                                                  | Sum of regional values                                             |
| Emissions\|HFC\|HFC134a                                                 | Sum of regional values                                             |
| Emissions\|HFC\|HFC143a                                                 | Sum of regional values                                             |
| Emissions\|HFC\|HFC227ea                                                | Sum of regional values                                             |
| Emissions\|HFC\|HFC23                                                   | Sum of regional values                                             |
| Emissions\|HFC\|HFC245fa                                                | Sum of regional values                                             |
| Emissions\|HFC\|HFC32                                                   | Sum of regional values                                             |
| Emissions\|Kyoto Gases                                                  | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|AFOLU                                           | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand                                  | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Residential and Commercial      | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Industry                        | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Industry\|Cement                | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Industry\|Chemicals             | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Industry\|Non-Ferrous Metals    | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Industry\|Iron and Steel        | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Industry\|Other Industry        | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Transportation                  | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Demand\|Other                           | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Supply                                  | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Supply\|Other                           | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Energy\|Supply\|Electricity                     | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Industrial Processes                            | Sum of regional values                                             |
| Emissions\|Kyoto Gases\|Other                                           | Sum of regional values                                             |
| Emissions\|N2O                                                          | Sum of regional values                                             |
| Emissions\|N2O\|AFOLU                                                   | Sum of regional values                                             |
| Emissions\|N2O\|Energy                                                  | Sum of regional values                                             |
| Emissions\|N2O\|Other                                                   | Sum of regional values                                             |
| Emissions\|NH3                                                          | Sum of regional values                                             |
| Emissions\|NH3\|AFOLU                                                   | Sum of regional values                                             |
| Emissions\|NH3\|Energy                                                  | Sum of regional values                                             |
| Emissions\|NH3\|Energy\|Demand\|Industry                                | Sum of regional values                                             |
| Emissions\|NH3\|Energy\|Demand\|Residential and Commercial              | Sum of regional values                                             |
| Emissions\|NH3\|Energy\|Demand\|Transportation                          | Sum of regional values                                             |
| Emissions\|NH3\|Energy\|Supply                                          | Sum of regional values                                             |
| Emissions\|NOx                                                          | Sum of regional values                                             |
| Emissions\|NOx\|AFOLU                                                   | Sum of regional values                                             |
| Emissions\|NOx\|Energy                                                  | Sum of regional values                                             |
| Emissions\|NOx\|Energy\|Demand\|Industry                                | Sum of regional values                                             |
| Emissions\|NOx\|Energy\|Demand\|Residential and Commercial              | Sum of regional values                                             |
| Emissions\|NOx\|Energy\|Demand\|Transportation                          | Sum of regional values                                             |
| Emissions\|NOx\|Energy\|Supply                                          | Sum of regional values                                             |
| Emissions\|OC                                                           | Sum of regional values                                             |
| Emissions\|OC\|AFOLU                                                    | Sum of regional values                                             |
| Emissions\|OC\|Energy                                                   | Sum of regional values                                             |
| Emissions\|OC\|Energy\|Demand\|Industry                                 | Sum of regional values                                             |
| Emissions\|OC\|Energy\|Demand\|Residential and Commercial               | Sum of regional values                                             |
| Emissions\|OC\|Energy\|Demand\|Transportation                           | Sum of regional values                                             |
| Emissions\|OC\|Energy\|Supply                                           | Sum of regional values                                             |
| Emissions\|PFC                                                          | Sum of regional values                                             |
| Emissions\|SF6                                                          | Sum of regional values                                             |
| Emissions\|Sulfur                                                       | Sum of regional values                                             |
| Emissions\|Sulfur\|AFOLU                                                | Sum of regional values                                             |
| Emissions\|Sulfur\|Energy                                               | Sum of regional values                                             |
| Emissions\|Sulfur\|Energy\|Demand\|Industry                             | Sum of regional values                                             |
| Emissions\|Sulfur\|Energy\|Demand\|Residential and Commercial           | Sum of regional values                                             |
| Emissions\|Sulfur\|Energy\|Demand\|Transportation                       | Sum of regional values                                             |
| Emissions\|Sulfur\|Energy\|Supply                                       | Sum of regional values                                             |
| Emissions\|VOC                                                          | Sum of regional values                                             |
| Emissions\|VOC\|AFOLU                                                   | Sum of regional values                                             |
| Emissions\|VOC\|Energy                                                  | Sum of regional values                                             |
| Emissions\|VOC\|Energy\|Demand\|Industry                                | Sum of regional values                                             |
| Emissions\|VOC\|Energy\|Demand\|Residential and Commercial              | Sum of regional values                                             |
| Emissions\|VOC\|Energy\|Demand\|Transportation                          | Sum of regional values                                             |
| Emissions\|VOC\|Energy\|Supply                                          | Sum of regional values                                             |
| Energy Service\|Residential and Commercial\|Floor Space                 | Sum of regional values                                             |
| Energy Service\|Residential and Commercial\|Residential\|Floor Space    | Sum of regional values                                             |
| Energy Service\|Transportation\|Freight                                 | Sum of regional values                                             |
| Energy Service\|Transportation\|Freight\|International Shipping         | Sum of regional values                                             |
| Energy Service\|Transportation\|Freight\|Navigation                     | Sum of regional values                                             |
| Energy Service\|Transportation\|Freight\|Railways                       | Sum of regional values                                             |
| Energy Service\|Transportation\|Freight\|Road                           | Sum of regional values                                             |
| Energy Service\|Transportation\|Passenger                               | Sum of regional values                                             |
| Energy Service\|Transportation\|Passenger\|Aviation                     | Sum of regional values                                             |
| Energy Service\|Transportation\|Passenger\|Bicycling and Walking        | Sum of regional values                                             |
| Energy Service\|Transportation\|Passenger\|Railways                     | Sum of regional values                                             |
| Energy Service\|Transportation\|Passenger\|Road                         | Sum of regional values                                             |
| Energy Service\|Transportation\|Passenger\|Road\|LDV                    | Sum of regional values                                             |
| Export\|Industry\|Steel\|Value                                          | Sum of regional values                                             |
| Final Energy                                                            | Sum of regional values                                             |
| Final Energy\|Electricity                                               | Sum of regional values                                             |
| Final Energy\|Gases                                                     | Sum of regional values                                             |
| Final Energy\|Heat                                                      | Sum of regional values                                             |
| Final Energy\|Hydrogen                                                  | Sum of regional values                                             |
| Final Energy\|Industry                                                  | Sum of regional values                                             |
| Final Energy\|Industry\|Cement                                          | Sum of regional values                                             |
| Final Energy\|Industry\|Cement\|Electricity                             | Sum of regional values                                             |
| Final Energy\|Industry\|Cement\|Gases                                   | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals                                       | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Ammonia                              | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Ammonia\|Gases                       | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Ammonia\|Hydrogen                    | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Ammonia\|Liquids                     | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Electricity                          | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Gases                                | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Heat                                 | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Hydrogen                             | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Liquids                              | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Solids                               | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Solids\|Bioenergy                    | Sum of regional values                                             |
| Final Energy\|Industry\|Chemicals\|Solids\|Fossil                       | Sum of regional values                                             |
| Final Energy\|Industry\|Electricity                                     | Sum of regional values                                             |
| Final Energy\|Industry\|Gases                                           | Sum of regional values                                             |
| Final Energy\|Industry\|Heat                                            | Sum of regional values                                             |
| Final Energy\|Industry\|Hydrogen                                        | Sum of regional values                                             |
| Final Energy\|Industry\|Liquids                                         | Sum of regional values                                             |
| Final Energy\|Industry\|Non-ferrous metals                              | Sum of regional values                                             |
| Final Energy\|Industry\|Non-ferrous metals\|Electricity                 | Sum of regional values                                             |
| Final Energy\|Industry\|Non-ferrous metals\|Gases                       | Sum of regional values                                             |
| Final Energy\|Industry\|Non-ferrous metals\|Liquids                     | Sum of regional values                                             |
| Final Energy\|Industry\|Non-ferrous metals\|Solids                      | Sum of regional values                                             |
| Final Energy\|Industry\|Non-ferrous metals\|Solids\|Bioenergy           | Sum of regional values                                             |
| Final Energy\|Industry\|Non-ferrous metals\|Solids\|Fossil              | Sum of regional values                                             |
| Final Energy\|Industry\|Solids                                          | Sum of regional values                                             |
| Final Energy\|Industry\|Solids\|Biomass                                 | Sum of regional values                                             |
| Final Energy\|Industry\|Solids\|Coal                                    | Sum of regional values                                             |
| Final Energy\|Industry\|Steel                                           | Sum of regional values                                             |
| Final Energy\|Industry\|Steel\|Electricity                              | Sum of regional values                                             |
| Final Energy\|Industry\|Steel\|Hydrogen                                 | Sum of regional values                                             |
| Final Energy\|Industry\|Steel\|Liquids                                  | Sum of regional values                                             |
| Final Energy\|Industry\|Steel\|Solids                                   | Sum of regional values                                             |
| Final Energy\|Industry\|Steel\|Solids\|Bioenergy                        | Sum of regional values                                             |
| Final Energy\|Industry\|Steel\|Solids\|Fossil                           | Sum of regional values                                             |
| Final Energy\|Liquids                                                   | Sum of regional values                                             |
| Final Energy\|Non-Energy Use                                            | Sum of regional values                                             |
| Final Energy\|Non-Energy Use\|Biomass                                   | Sum of regional values                                             |
| Final Energy\|Non-Energy Use\|Coal                                      | Sum of regional values                                             |
| Final Energy\|Non-Energy Use\|Gas                                       | Sum of regional values                                             |
| Final Energy\|Non-Energy Use\|Oil                                       | Sum of regional values                                             |
| Final Energy\|Other Sector                                              | Sum of regional values                                             |
| Final Energy\|Other Sector\|Electricity                                 | Sum of regional values                                             |
| Final Energy\|Residential and Commercial                                | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Cooling           | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Electricity       | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Gases             | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Heat              | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Heating\|Space    | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Hydrogen          | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Liquids           | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Solids            | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Solids\|Biomass   | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Commercial\|Solids\|Coal      | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Cooling                       | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Electricity                   | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Gases                         | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Heat                          | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Heating\|Space                | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Hydrogen                      | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Liquids                       | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Residential\|Cooling          | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Residential\|Electricity      | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Residential\|Gases            | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Residential\|Heat             | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Residential\|Heating\|Space   | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Residential\|Hydrogen         | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Residential\|Liquids          | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Solids                        | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Solids\|Biomass               | Sum of regional values                                             |
| Final Energy\|Residential and Commercial\|Solids\|Coal                  | Sum of regional values                                             |
| Final Energy\|Solids                                                    | Sum of regional values                                             |
| Final Energy\|Solids\|Biomass                                           | Sum of regional values                                             |
| Final Energy\|Solids\|Coal                                              | Sum of regional values                                             |
| Final Energy\|Transportation                                            | Sum of regional values                                             |
| Final Energy\|Transportation\|Aviation                                  | Sum of regional values                                             |
| Final Energy\|Transportation\|Aviation\|Passenger                       | Sum of regional values                                             |
| Final Energy\|Transportation\|Electricity                               | Sum of regional values                                             |
| Final Energy\|Transportation\|Freight                                   | Sum of regional values                                             |
| Final Energy\|Transportation\|Freight\|Electricity                      | Sum of regional values                                             |
| Final Energy\|Transportation\|Freight\|Hydrogen                         | Sum of regional values                                             |
| Final Energy\|Transportation\|Freight\|Liquids                          | Sum of regional values                                             |
| Final Energy\|Transportation\|Freight\|Other                            | Sum of regional values                                             |
| Final Energy\|Transportation\|Gases                                     | Sum of regional values                                             |
| Final Energy\|Transportation\|Hydrogen                                  | Sum of regional values                                             |
| Final Energy\|Transportation\|Liquids                                   | Sum of regional values                                             |
| Final Energy\|Transportation\|Maritime                                  | Sum of regional values                                             |
| Final Energy\|Transportation\|Maritime\|Freight                         | Sum of regional values                                             |
| Final Energy\|Transportation\|Other                                     | Sum of regional values                                             |
| Final Energy\|Transportation\|Passenger                                 | Sum of regional values                                             |
| Final Energy\|Transportation\|Passenger\|Electricity                    | Sum of regional values                                             |
| Final Energy\|Transportation\|Passenger\|Gases                          | Sum of regional values                                             |
| Final Energy\|Transportation\|Passenger\|Hydrogen                       | Sum of regional values                                             |
| Final Energy\|Transportation\|Passenger\|Liquids                        | Sum of regional values                                             |
| Final Energy\|Transportation\|Rail                                      | Sum of regional values                                             |
| Final Energy\|Transportation\|Rail\|Freight                             | Sum of regional values                                             |
| Final Energy\|Transportation\|Rail\|Passenger                           | Sum of regional values                                             |
| Final Energy\|Transportation\|Road                                      | Sum of regional values                                             |
| Final Energy\|Transportation\|Road\|Freight                             | Sum of regional values                                             |
| Final Energy\|Transportation\|Road\|Freight\|Electric                   | Sum of regional values                                             |
| Final Energy\|Transportation\|Road\|Freight\|FC                         | Sum of regional values                                             |
| Final Energy\|Transportation\|Road\|Passenger                           | Sum of regional values                                             |
| Final Energy\|Transportation\|Road\|Passenger\|2W&3W                    | Sum of regional values                                             |
| Final Energy\|Transportation\|Road\|Passenger\|Bus                      | Sum of regional values                                             |
| Final Energy\|Transportation\|Road\|Passenger\|4W                       | Sum of regional values                                             |
| Final Energy\|Water                                                     | Sum of regional values                                             |
| Final Energy\|Water\|Desalination                                       | Sum of regional values                                             |
| Final Energy\|Water\|Desalination\|Electricity                          | Sum of regional values                                             |
| Final Energy\|Water\|Desalination\|Gases                                | Sum of regional values                                             |
| Final Energy\|Water\|Desalination\|Liquids                              | Sum of regional values                                             |
| Final Energy\|Water\|Industry                                           | Sum of regional values                                             |
| Final Energy\|Water\|Industry\|Electricity                              | Sum of regional values                                             |
| Final Energy\|Water\|Irrigation                                         | Sum of regional values                                             |
| Final Energy\|Water\|Irrigation\|Electricity                            | Sum of regional values                                             |
| Final Energy\|Water\|Municipal                                          | Sum of regional values                                             |
| Final Energy\|Water\|Municipal\|Electricity                             | Sum of regional values                                             |
| Forcing                                                                 | Global value                                                       |
| GDP\|MER                                                                | Sum of regional values                                             |
| GDP\|PPP                                                                | Sum of regional values                                             |
| Import\|Industry\|Steel\|Value                                          | Sum of regional values                                             |
| Investment\|Energy Supply\|CO2 Transport and Storage                    | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity                                  | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Biomass                         | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Biomass\|w/ CCS                 | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Biomass\|w/o CCS                | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Coal                            | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Coal\|w/ CCS                    | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Coal\|w/o CCS                   | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Gas                             | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Gas\|w/ CCS                     | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Gas\|w/o CCS                    | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Geothermal                      | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Hydro                           | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Non-Biomass Renewables          | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Nuclear                         | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Oil                             | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Oil\|w/ CCS                     | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Oil\|w/o CCS                    | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Solar                           | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Transmission and Distribution   | Sum of regional values                                             |
| Investment\|Energy Supply\|Electricity\|Wind                            | Sum of regional values                                             |
| Investment\|Energy Supply\|Extraction\|Coal                             | Sum of regional values                                             |
| Investment\|Energy Supply\|Extraction\|Fossil                           | Sum of regional values                                             |
| Investment\|Energy Supply\|Extraction\|Gas                              | Sum of regional values                                             |
| Investment\|Energy Supply\|Extraction\|Oil                              | Sum of regional values                                             |
| Land Cover                                                              | Sum of regional values                                             |
| Land Cover\|Built-up Area                                               | Sum of regional values                                             |
| Land Cover\|Cropland                                                    | Sum of regional values                                             |
| Land Cover\|Cropland\|Energy Crops                                      | Sum of regional values                                             |
| Land Cover\|Forest                                                      | Sum of regional values                                             |
| Land Cover\|Forest\|Managed                                             | Sum of regional values                                             |
| Land Cover\|Forest\|Natural Forest                                      | Sum of regional values                                             |
| Land Cover\|Other Land                                                  | Sum of regional values                                             |
| Land Cover\|Pasture                                                     | Sum of regional values                                             |
| Population                                                              | Sum of regional values                                             |
| Price\|Agriculture\|Crops\|Index                                        | Weighted sum of regional values by commodity                                           |
| Price\|Agriculture\|Crops\|Food\|Index                                  | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|Corn\|Index                            | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|FiberCrop\|Index                       | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|Fruits\|Index                          | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|Legumes\|Index                         | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|MiscCrop\|Index                        | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|NutsSeeds\|Index                       | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|OilCrop\|Index                         | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|OilPalm\|Index                         | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|OtherGrain\|Index                      | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|Rice\|Index                            | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|RootTuber\|Index                       | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|Soybean\|Index                         | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|SugarCrop\|Index                       | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|Vegetables\|Index                      | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Food\|Wheat\|Index                           | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Feed\|Index                                  | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Energy\|Index                                | Mean of regional values                                            |
| Price\|Agriculture\|Crops\|Other\|Index                                 | Mean of regional values                                            |
| Price\|Agriculture\|Livestock\|Food\|Index                              | Mean of regional values                                            |
| Price\|Agriculture\|Livestock\|Food\|Beef\|Index                        | Mean of regional values                                            |
| Price\|Agriculture\|Livestock\|Food\|Dairy\|Index                       | Mean of regional values                                            |
| Price\|Agriculture\|Livestock\|Food\|Pork\|Index                        | Mean of regional values                                            |
| Price\|Agriculture\|Livestock\|Food\|Poultry\|Index                     | Mean of regional values                                            |
| Price\|Agriculture\|Livestock\|Food\|SheepGoat\|Index                   | Mean of regional values                                            |
| Price\|Agriculture\|Livestock\|Other\|Index                             | Mean of regional values                                            |
| Price\|Carbon                                                           | Weighted sum of regional values by CO2 emissions                   |
| Price\|Carbon\|Energy                                                   | Sum of regional values                                             |
| Price\|Carbon\|Energy\|Demand\|Industry                                 | Sum of regional values                                             |
| Price\|Carbon\|Energy\|Demand\|Residential and Commercial               | Sum of regional values                                             |
| Price\|Carbon\|Energy\|Demand\|Transportation                           | Sum of regional values                                             |
| Price\|Carbon\|Energy\|Supply                                           | Sum of regional values                                             |
| Price\|Final Energy\|Buildings\|Residential                             | Mean of regional values                                            |
| Price\|Final Energy\|Buildings\|Residential\|Electricity                | Mean of regional values                                            |
| Price\|Final Energy\|Buildings\|Residential\|Electricity\|Index         | Mean of regional values                                            |
| Price\|Final Energy\|Buildings\|Residential\|Gases\|Gas                 | Mean of regional values                                            |
| Price\|Final Energy\|Buildings\|Residential\|Gases\|Gas\|Index          | Mean of regional values                                            |
| Price\|Final Energy\|Buildings\|Residential\|Liquids                    | Mean of regional values                                            |
| Price\|Final Energy\|Buildings\|Residential\|Solids                     | Mean of regional values                                            |
| Price\|Final Energy\|Buildings\|Residential\|Solids\|Biomass            | Mean of regional values                                            |
| Price\|Final Energy\|Buildings\|Residential\|Solids\|Coal               | Mean of regional values                                            |
| Price\|Final Energy\|Industry                                           | Mean of regional values                                            |
| Price\|Final Energy\|Industry\|Electricity                              | Mean of regional values                                            |
| Price\|Final Energy\|Industry\|Gases                                    | Mean of regional values                                            |
| Price\|Final Energy\|Industry\|Liquids                                  | Mean of regional values                                            |
| Price\|Final Energy\|Industry\|Solids                                   | Mean of regional values                                            |
| Price\|Final Energy\|Industry\|Solids\|Biomass                          | Mean of regional values                                            |
| Price\|Final Energy\|Industry\|Solids\|Coal                             | Mean of regional values                                            |
| Price\|Final Energy\|Transportation                                     | Mean of regional values                                            |
| Price\|Final Energy\|Transportation\|Electricity                        | Mean of regional values                                            |
| Price\|Final Energy\|Transportation\|Gases                              | Mean of regional values                                            |
| Price\|Final Energy\|Transportation\|Liquids                            | Mean of regional values                                            |
| Price\|Primary Energy                                                   | Mean of regional values                                            |
| Price\|Primary Energy\|Biomass                                          | Mean of regional values                                            |
| Price\|Primary Energy\|Biomass\|Index                                   | Mean of regional values                                            |
| Price\|Primary Energy\|Coal                                             | Mean of regional values                                            |
| Price\|Primary Energy\|Coal\|Index                                      | Mean of regional values                                            |
| Price\|Primary Energy\|Gas                                              | Mean of regional values                                            |
| Price\|Primary Energy\|Gas\|Index                                       | Mean of regional values                                            |
| Price\|Primary Energy\|Oil                                              | Mean of regional values                                            |
| Price\|Primary Energy\|Oil\|Index                                       | Mean of regional values                                            |
| Price\|Secondary Energy                                                 | Mean of regional values                                            |
| Price\|Secondary Energy\|Electricity                                    | Mean of regional values                                            |
| Price\|Secondary Energy\|Electricity\|Index                             | Mean of regional values                                            |
| Primary Energy                                                          | Sum of regional values                                             |
| Primary Energy\|Biomass                                                 | Sum of regional values                                             |
| Primary Energy\|Biomass\|1st Generation                                 | Sum of regional values                                             |
| Primary Energy\|Biomass\|Modern                                         | Sum of regional values                                             |
| Primary Energy\|Coal                                                    | Sum of regional values                                             |
| Primary Energy\|Coal\|w/ CCS                                            | Sum of regional values                                             |
| Primary Energy\|Coal\|w/o CCS                                           | Sum of regional values                                             |
| Primary Energy\|Fossil                                                  | Sum of regional values                                             |
| Primary Energy\|Fossil\|w/ CCS                                          | Sum of regional values                                             |
| Primary Energy\|Fossil\|w/o CCS                                         | Sum of regional values                                             |
| Primary Energy\|Gas                                                     | Sum of regional values                                             |
| Primary Energy\|Gas\|w/ CCS                                             | Sum of regional values                                             |
| Primary Energy\|Gas\|w/o CCS                                            | Sum of regional values                                             |
| Primary Energy\|Non-Biomass Renewables                                  | Sum of regional values                                             |
| Primary Energy\|Non-Biomass Renewables\|Geothermal                      | Sum of regional values                                             |
| Primary Energy\|Non-Biomass Renewables\|Hydro                           | Sum of regional values                                             |
| Primary Energy\|Non-Biomass Renewables\|Solar                           | Sum of regional values                                             |
| Primary Energy\|Non-Biomass Renewables\|Wind                            | Sum of regional values                                             |
| Primary Energy\|Nuclear                                                 | Sum of regional values                                             |
| Primary Energy\|Oil                                                     | Sum of regional values                                             |
| Primary Energy\|Oil\|w/ CCS                                             | Sum of regional values                                             |
| Primary Energy\|Oil\|w/o CCS                                            | Sum of regional values                                             |
| Primary Energy\|Secondary Energy Trade                                  | Sum of regional values                                             |
| Production\|Cement                                                      | Sum of regional values                                             |
| Production\|Non-ferrous metals                                          | Sum of regional values                                             |
| Production\|Steel                                                       | Sum of regional values                                             |
| Revenue\|Government\|Tax\|Carbon                                        | Sum of regional values                                             |
| Revenue\|Government\|Tax\|Carbon\|Demand\|Buildings                     | Sum of regional values                                             |
| Revenue\|Government\|Tax\|Carbon\|Demand\|Industry                      | Sum of regional values                                             |
| Revenue\|Government\|Tax\|Carbon\|Demand\|Transport                     | Sum of regional values                                             |
| Revenue\|Government\|Tax\|Carbon\|Supply                                | Sum of regional values                                             |
| Secondary Energy                                                        | Sum of regional values                                             |
| Secondary Energy\|Electricity                                           | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Biomass                                  | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Biomass\|w/ CCS                          | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Biomass\|w/o CCS                         | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Coal                                     | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Coal\|w/ CCS                             | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Coal\|w/o CCS                            | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Gas                                      | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Gas\|w/ CCS                              | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Gas\|w/o CCS                             | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Geothermal                               | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Hydro                                    | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Non-Biomass Renewables                   | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Nuclear                                  | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Oil                                      | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Oil\|w/o CCS                             | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Solar                                    | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Solar\|CSP                               | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Solar\|PV                                | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Wind                                     | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Wind\|Offshore                           | Sum of regional values                                             |
| Secondary Energy\|Electricity\|Wind\|Onshore                            | Sum of regional values                                             |
| Secondary Energy\|Gases                                                 | Sum of regional values                                             |
| Secondary Energy\|Gases\|Biomass                                        | Sum of regional values                                             |
| Secondary Energy\|Gases\|Coal                                           | Sum of regional values                                             |
| Secondary Energy\|Gases\|Natural Gas                                    | Sum of regional values                                             |
| Secondary Energy\|Hydrogen                                              | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Biomass                                     | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Biomass\|w/ CCS                             | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Biomass\|w/o CCS                            | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Coal                                        | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Coal\|w/ CCS                                | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Electricity                                 | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Fossil                                      | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Fossil\|w/ CCS                              | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Fossil\|w/o CCS                             | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Gas                                         | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Gas\|w/ CCS                                 | Sum of regional values                                             |
| Secondary Energy\|Hydrogen\|Gas\|w/o CCS                                | Sum of regional values                                             |
| Secondary Energy\|Liquids                                               | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Biomass                                      | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Biomass\|w/ CCS                              | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Biomass\|w/o CCS                             | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Coal                                         | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Coal\|w/ CCS                                 | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Coal\|w/o CCS                                | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Fossil                                       | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Fossil\|w/ CCS                               | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Fossil\|w/o CCS                              | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Gas                                          | Sum of regional values                                             |
| Secondary Energy\|Liquids\|Oil                                          | Sum of regional values                                             |
| Secondary Energy\|Solids                                                | Sum of regional values                                             |
| Secondary Energy\|Solids\|Biomass                                       | Sum of regional values                                             |
| Secondary Energy\|Solids\|Coal                                          | Sum of regional values                                             |
| Temperature\|Global Mean                                                | Global value                                                       |
| Trade\|Primary Energy\|Coal\|Volume                                     | Sum of regional values                                             |
| Trade\|Primary Energy\|Gas\|Volume                                      | Sum of regional values                                             |
| Trade\|Primary Energy\|Oil\|Volume                                      | Sum of regional values                                             |
